# Generated by Django 4.1.2 on 2022-10-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.CharField(default='a', max_length=150, verbose_name='Назва гравця'),
        ),
    ]
